version: '3.8'

services:

  mysql-coupon:
    image: mysql
    container_name: mysql-coupon
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coupon
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - coupon-mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  coupon-mysql-data:
