version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql-coupon:
    image: mysql:latest
    container_name: mysql-coupon
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=coupon
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-coupon-data:/var/lib/mysql

volumes:
  mongo-data:
  mysql-coupon-data:
